
main: main.DeathCoordinatesTPD
version: 0.0.2
name: DeathCoordinatesTPD
author: DiosAlex
api-version: 1.13

commands:
  deathcoordinatesalex:
    description: Main command;
    aliases:
      - tpd

